"""baseline

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-06-02 17:28:05.972281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('app_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('categories',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('tag_id', sa.String(length=64), nullable=True),
    sa.Column('tag_slug', sa.String(length=128), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('image_path', sa.String(length=256), nullable=True),
    sa.Column('image_status', sa.String(length=12), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('prompt_override', sa.Text(), nullable=True),
    sa.Column('image_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('ix_categories_sort', ['hidden', 'pinned', 'display_order'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_account_id', sa.BigInteger(), nullable=True),
    sa.Column('referral_code', sa.String(length=32), nullable=True),
    sa.Column('referred_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("language in ('en','fa','ru','zh')", name='ck_user_lang'),
    sa.CheckConstraint("status in ('active','suspended','banned')", name='ck_user_status'),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('signature_type', sa.SmallInteger(), nullable=False),
    sa.Column('funder_address', sa.String(length=64), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=False),
    sa.Column('encrypted_api_creds', sa.Text(), nullable=True),
    sa.Column('key_version', sa.SmallInteger(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("mode in ('demo','live')", name='ck_account_mode'),
    sa.CheckConstraint('signature_type in (0,1,2)', name='ck_account_sigtype'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'label', name='uq_account_user_label')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_wallet_address'), ['wallet_address'], unique=False)

    op.create_table('bot_states',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=8), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('changed_by', sa.String(length=16), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('gemini_usage',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gemini_usage', schema=None) as batch_op:
        batch_op.create_index('ix_gemini_usage_ts', ['ts'], unique=False)

    op.create_table('points_ledger',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_ledger_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_points_user', ['user_id'], unique=False)

    op.create_table('referrals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('inviter_id', sa.BigInteger(), nullable=False),
    sa.Column('invitee_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitee_id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_inviter_id'), ['inviter_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('confirm_trades', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=48), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_stats',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.String(length=10), nullable=True),
    sa.Column('total_bets', sa.Integer(), nullable=False),
    sa.Column('total_volume_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('settled_bets', sa.Integer(), nullable=False),
    sa.Column('realized_pnl_usd', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('brier_sum', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.create_index('ix_user_stats_bets', ['total_bets'], unique=False)
        batch_op.create_index('ix_user_stats_volume', ['total_volume_usd'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_type', sa.String(length=12), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('event', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_event'), ['event'], unique=False)
        batch_op.create_index('ix_audit_ts', ['ts'], unique=False)

    op.create_table('bets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('market_id', sa.String(length=128), nullable=False),
    sa.Column('token_id', sa.String(length=128), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=8), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('shares', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('payout_usd', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('pnl_usd', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('brier', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('clob_order_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bets_status'), ['status'], unique=False)
        batch_op.create_index('ix_bets_status_market', ['status', 'market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bets_user_id'), ['user_id'], unique=False)

    op.create_table('commands',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index('ix_commands_status_time', ['status', 'requested_at'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('clob_order_id', sa.String(length=128), nullable=True),
    sa.Column('token_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('filled_size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fill_method', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_account_status', ['account_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_clob_order_id'), ['clob_order_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('token_id', sa.String(length=128), nullable=False),
    sa.Column('market_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('cur_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'token_id', name='uq_position_account_token')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_account_id'), ['account_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('token_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('cost', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('fill_method', sa.String(length=32), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('ix_trades_account_time', ['account_id', 'executed_at'], unique=False)
        batch_op.create_index('ix_trades_executed_at', ['executed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trades_executed_at')
        batch_op.drop_index('ix_trades_account_time')

    op.drop_table('trades')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_account_id'))

    op.drop_table('positions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_clob_order_id'))
        batch_op.drop_index('ix_orders_account_status')

    op.drop_table('orders')
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index('ix_commands_status_time')

    op.drop_table('commands')
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bets_user_id'))
        batch_op.drop_index('ix_bets_status_market')
        batch_op.drop_index(batch_op.f('ix_bets_status'))

    op.drop_table('bets')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_ts')
        batch_op.drop_index(batch_op.f('ix_audit_log_event'))

    op.drop_table('audit_log')
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_user_stats_volume')
        batch_op.drop_index('ix_user_stats_bets')

    op.drop_table('user_stats')
    op.drop_table('user_settings')
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_inviter_id'))

    op.drop_table('referrals')
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_points_user')
        batch_op.drop_index(batch_op.f('ix_points_ledger_user_id'))

    op.drop_table('points_ledger')
    with op.batch_alter_table('gemini_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_gemini_usage_ts')

    op.drop_table('gemini_usage')
    op.drop_table('bot_states')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_wallet_address'))
        batch_op.drop_index(batch_op.f('ix_accounts_user_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))

    op.drop_table('users')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_sort')

    op.drop_table('categories')
    op.drop_table('app_config')
    op.drop_table('admins')
    # ### end Alembic commands ###
