"""news_pipeline

Revision ID: 0002_news_pipeline
Revises: 0001_baseline
Create Date: 2026-06-02 17:28:20.320137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_news_pipeline'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_sources',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('lang_hint', sa.String(length=8), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind in ('auto','rss','html','telegram')", name='ck_news_source_kind'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    with op.batch_alter_table('news_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_sources_enabled'), ['enabled'], unique=False)
        batch_op.create_index('ix_news_sources_enabled_cat', ['enabled', 'category_id'], unique=False)

    op.create_table('user_news_prefs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('delivery', sa.String(length=8), nullable=False),
    sa.Column('digest_hour', sa.SmallInteger(), nullable=False),
    sa.Column('quiet_start', sa.SmallInteger(), nullable=True),
    sa.Column('quiet_end', sa.SmallInteger(), nullable=True),
    sa.Column('only_relevant', sa.Boolean(), nullable=False),
    sa.Column('max_per_digest', sa.SmallInteger(), nullable=False),
    sa.Column('last_digest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("delivery in ('off','daily','realtime')", name='ck_news_prefs_delivery'),
    sa.CheckConstraint('digest_hour >= 0 and digest_hour <= 23', name='ck_news_prefs_hour'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user_news_prefs', schema=None) as batch_op:
        batch_op.create_index('ix_news_prefs_delivery', ['delivery'], unique=False)

    op.create_table('user_topic_follows',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    with op.batch_alter_table('user_topic_follows', schema=None) as batch_op:
        batch_op.create_index('ix_topic_follows_category', ['category_id'], unique=False)

    op.create_table('news_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=True),
    sa.Column('lang_orig', sa.String(length=8), nullable=True),
    sa.Column('title_orig', sa.Text(), nullable=False),
    sa.Column('body_orig', sa.Text(), nullable=True),
    sa.Column('hero_image_url', sa.String(length=2048), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('rendered_image_path', sa.String(length=512), nullable=True),
    sa.Column('image_status', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('excluded_from_autopublish', sa.Boolean(), nullable=False),
    sa.Column('market_id', sa.String(length=128), nullable=True),
    sa.Column('cta_market_id', sa.String(length=128), nullable=True),
    sa.Column('cta_url', sa.String(length=512), nullable=True),
    sa.Column('cta_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel_msg_id', sa.BigInteger(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("image_status in ('none','generating','ready','failed')", name='ck_news_item_image_status'),
    sa.CheckConstraint("status in ('backlog','approved','translating','rendering','ready','sent','rejected')", name='ck_news_item_status'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index('ix_news_items_cat_status', ['category_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_dedup_hash'), ['dedup_hash'], unique=False)
        batch_op.create_index('ix_news_items_published', ['published_at'], unique=False)
        batch_op.create_index('ix_news_items_status_score', ['status', 'score'], unique=False)

    op.create_table('news_channel_posts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('news_item_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_item_id', 'chat_id', 'lang', name='uq_news_channel_post')
    )
    op.create_table('news_delivered',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('news_item_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'news_item_id')
    )
    with op.batch_alter_table('news_delivered', schema=None) as batch_op:
        batch_op.create_index('ix_news_delivered_item', ['news_item_id'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        # server_default backfills existing category rows ('market'); the model
        # uses a Python-side default, so new inserts set it explicitly.
        batch_op.add_column(sa.Column('kind', sa.String(length=12), nullable=False, server_default='market'))
        batch_op.create_check_constraint('ck_category_kind', "kind in ('market','news','both')")
        batch_op.create_index(batch_op.f('ix_categories_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_kind'))
        batch_op.drop_constraint('ck_category_kind', type_='check')
        batch_op.drop_column('kind')

    with op.batch_alter_table('news_delivered', schema=None) as batch_op:
        batch_op.drop_index('ix_news_delivered_item')

    op.drop_table('news_delivered')
    op.drop_table('news_channel_posts')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index('ix_news_items_status_score')
        batch_op.drop_index('ix_news_items_published')
        batch_op.drop_index(batch_op.f('ix_news_items_dedup_hash'))
        batch_op.drop_index('ix_news_items_cat_status')

    op.drop_table('news_items')
    with op.batch_alter_table('user_topic_follows', schema=None) as batch_op:
        batch_op.drop_index('ix_topic_follows_category')

    op.drop_table('user_topic_follows')
    with op.batch_alter_table('user_news_prefs', schema=None) as batch_op:
        batch_op.drop_index('ix_news_prefs_delivery')

    op.drop_table('user_news_prefs')
    with op.batch_alter_table('news_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_news_sources_enabled_cat')
        batch_op.drop_index(batch_op.f('ix_news_sources_enabled'))

    op.drop_table('news_sources')
    # ### end Alembic commands ###
